from __future__ import annotations

import os

CAPTURE_DELAY_S = 0.3

SCALE_FACTOR = 2
MIN_SCALED_DIM_PX = 200
MAX_SCALED_DIM_PX = 4096

BORDER_PADDING_PX = 40

PADDLE_LANG = "en"
PADDLE_USE_ANGLE_CLS = True
PADDLE_USE_GPU = False
PADDLE_DET_DB_THRESH = 0.3
PADDLE_DET_DB_BOX_THRESH = 0.5
PADDLE_DET_DB_UNCLIP_RATIO = 2.0
PADDLE_USE_DILATION = True
PADDLE_DET_LIMIT_SIDE_LEN = 4096
PADDLE_MIN_CONFIDENCE = 0.5

OVERLAY_MIN_DRAG_PX = 5
OVERLAY_BACKGROUND_COLOR = "#222222"
OVERLAY_OPACITY = 0.65
OVERLAY_TRANSPARENT_COLOR = "#000000"
OVERLAY_SELECTION_COLOR = "#3b82f6"
OVERLAY_SELECTION_LINE_WIDTH = 2

_OCR_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.abspath(os.path.join(_OCR_MODULE_DIR, "..", "..", ".."))
DEBUG_OUTPUT_DIR: str = os.path.join(_PROJECT_ROOT, "debug", "ocr")
