from __future__ import annotations

CAPTURE_DELAY_S = 0.3

CANDIDATE_LANGUAGES = ("en-US", "id-ID", "en-GB")

SCALE_FACTOR = 3
MIN_SCALED_DIM_PX = 200
MAX_SCALED_DIM_PX = 4096

BORDER_PADDING_PX = 40
DARK_MEAN_THRESHOLD = 127

OVERLAY_MIN_DRAG_PX = 5
OVERLAY_BACKGROUND_COLOR = "#222222"
OVERLAY_OPACITY = 0.65
OVERLAY_TRANSPARENT_COLOR = "#000000"
OVERLAY_SELECTION_COLOR = "#3b82f6"
OVERLAY_SELECTION_LINE_WIDTH = 2
