"""Standalone tuning constants, grouped by domain."""

# -- Spectrum Analyzer --
SPECTRUM_DB_FLOOR = -60.0
SPECTRUM_DB_CEILING = 0.0
SPECTRUM_SMOOTHING_ATTACK = 0.4
SPECTRUM_SMOOTHING_DECAY = 0.15
SPECTRUM_MIN_MAGNITUDE = 1e-10

# -- Speech Pause Model --
PAUSE_COMMA_MS = 250.0
PAUSE_SEMICOLON_MS = 300.0
PAUSE_COLON_MS = 350.0
PAUSE_PERIOD_MS = 500.0
PAUSE_QUESTION_MS = 550.0
PAUSE_EXCLAMATION_MS = 500.0
PAUSE_DASH_MS = 200.0
PAUSE_ELLIPSIS_MS = 600.0
BREATH_INTERVAL_WORDS = 12
PAUSE_BREATH_MS = 400.0

# -- Audio Player --
AUDIO_BLOCK_SIZE = 1024
AUDIO_DEFAULT_SAMPLERATE = 24000
AUDIO_DEQUEUE_TIMEOUT_S = 0.5
AUDIO_THREAD_JOIN_TIMEOUT_S = 2.0

# -- Database --
DB_BUSY_TIMEOUT_MS = 5000
